# nginx proxy address - http://172.17.0.1:59072

name: pocketid
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/pocket-id/pocket-id:latest
    container_name: pocketid-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      TRUST_PROXY: "true"
      APP_URL: https://${BASE_HOST_NAME:-localhost}.${BASE_DOMAIN_NAME:-example.com}
      MAXMIND_LICENSE_KEY: ${MAXMIND_LICENSE_KEY:-}
      CONTAINER_NAME: pocketid-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    ports:
      - '172.17.0.1:59072:1411'
    volumes:
      - './volumes/data/pocketid:/app/data:z'
    healthcheck:
      test: 'curl -f http://localhost:1411/healthz'
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    networks:
      - pocketid
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://pocketid-app:1411'
      - 'cloudflare.hostname=pocketid.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.pocketid-app.entrypoints=http'
      - 'traefik.http.routers.pocketid-app-secure.tls=true'
      - 'traefik.http.routers.pocketid-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.pocketid-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.pocketid-app.middlewares=pocketid-app-https-redirect'
      - 'traefik.http.routers.pocketid-app-secure.entrypoints=https'
      - 'traefik.http.routers.pocketid-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.pocketid-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.pocketid-app-secure.service=pocketid-app'
      - 'traefik.http.services.pocketid-app.loadbalancer.server.port=1411'

networks:
  pocketid:
    name: pocketid
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
